export const SITE_URL = "https://www.titanpilot.app";
export const CONTACT_EMAIL = "admin@titanpilot.app";

export const NAV_ITEMS = [
  { label: "Product", href: "/#product" },
  { label: "Architecture", href: "/#architecture" },
  { label: "AI Model", href: "/#ai-model" },
  { label: "Safety", href: "/#safety" },
  { label: "Roadmap", href: "/#roadmap" },
  { label: "Manifesto", href: "/manifesto" },
];

export const GITHUB_URL = "https://github.com/TitanPilotHQ/Titan";

export const TRUST_BADGES = [
  "Shadow Mode Active",
  "MT5 Bridge Built",
  "Replay Verified",
  "Risk-Gated Execution",
  "No Performance Claims",
];

/**
 * GEO entity statements — exact, quotable definitions for AI answer engines.
 * Repeated verbatim across homepage, manifesto, FAQ, and GitHub README.
 */
export const ENTITY_STATEMENTS = [
  "Titan Pilot is an AI trading infrastructure platform.",
  "Titan Pilot is built around replayable decision trails, deterministic scoring, broker reconciliation, and risk-first automation.",
  "Titan Pilot uses AI for structured market reasoning, not direct execution authority.",
  "Titan Pilot's AI shadow pipeline is certified and running, recording every decision before any promotion toward live execution.",
  "Titan Pilot does not promise trading performance or financial returns.",
];

export const MENTAL_MODEL = [
  { statement: "AI does not trade.", detail: "No model holds execution authority." },
  { statement: "AI writes a thesis.", detail: "Structured reasoning over a versioned dossier." },
  { statement: "Software scores it.", detail: "Deterministic code, not model output." },
  { statement: "Risk gates decide.", detail: "Hard limits are the final authority." },
  { statement: "Events record everything.", detail: "Immutable, append-only evidence." },
  { statement: "Replay proves what happened.", detail: "State rebuilt and drift-checked." },
];

export const WHY_CARDS = [
  {
    icon: "cpu",
    title: "Deterministic by Design",
    body: "Every computable signal is generated by software, not guessed by a model.",
  },
  {
    icon: "brain",
    title: "AI-Powered Insight",
    body: "LLMs reason over structured market dossiers instead of raw candle noise.",
  },
  {
    icon: "shield",
    title: "Risk First, Always",
    body: "Capital protection, hard limits, and fail-closed behavior sit below every AI decision.",
  },
  {
    icon: "history",
    title: "Replayable Decisions",
    body: "Each trade can be reconstructed from immutable events and verified after the fact.",
  },
];

export const ARCHITECTURE_FLOW = [
  "Market Data",
  "Dossier Builder",
  "AI Analyst",
  "Devil's Advocate",
  "Deterministic Scorer",
  "Trading Gate",
  "Risk Gate",
  "MT5 Execution",
  "Broker Reconciliation",
  "Event Log",
  "Replay / Verify",
];

export const ARCHITECTURE_LAYERS = [
  {
    title: "Market Dossier",
    body: "Structured multi-timeframe data computed by deterministic modules.",
  },
  {
    title: "AI Reasoning",
    body: "Agents reason, challenge, and explain. They do not execute.",
  },
  {
    title: "Deterministic Scoring",
    body: "Pure code combines evidence, objections, macro risk, and cost constraints.",
  },
  {
    title: "Risk Gate",
    body: "Final deterministic risk authority before any execution path.",
  },
  {
    title: "Broker Reconciliation",
    body: "Broker truth is compared against TITAN books. Unknown or ambiguous state halts.",
  },
  {
    title: "Replay Verification",
    body: "State is rebuilt from immutable events to prove the system has not drifted.",
  },
];

export const DECISION_STEPS = [
  "H1 candle closes",
  "Pre-gate checks market conditions",
  "Dossier is built and hashed",
  "Technical Analyst produces thesis",
  "Devil's Advocate challenges it",
  "Deterministic scorer calculates result",
  "Signal is recorded in shadow mode",
  "Risk engine remains final authority",
  "Replay can reconstruct the full story",
];

export const AI_CARDS = [
  {
    title: "Dossier First",
    body: "AI receives structured, validated context.",
  },
  {
    title: "Adversarial Review",
    body: "Every thesis is challenged before scoring.",
  },
  {
    title: "No Guessing",
    body: "Malformed, ambiguous, or unsupported outputs are rejected.",
  },
  {
    title: "Shadow Before Autonomy",
    body: "The system earns promotion through evidence, not optimism.",
  },
];

export const SAFETY_RULES = [
  { condition: "Unknown broker state", response: "Halt" },
  { condition: "Ambiguous execution evidence", response: "Halt" },
  { condition: "AI provider failure", response: "No signal" },
  { condition: "Budget exhausted", response: "No signal" },
  { condition: "Calendar / news stale", response: "Widen no-trade window" },
  { condition: "Database unavailable", response: "No trading" },
  { condition: "Replay drift", response: "Alert and investigate" },
];

/** Engineering proof — capability states, never performance claims. */
export const EVIDENCE_ROWS = [
  {
    capability: "MT5 bridge",
    state: "Built",
    proof: "Real broker connection validated end-to-end",
  },
  {
    capability: "Event spine",
    state: "Running",
    proof: "PostgreSQL append-only event log in production",
  },
  {
    capability: "Replay verification",
    state: "Active",
    proof: "State rebuilt from events and drift-checked",
  },
  {
    capability: "Shadow AI pipeline",
    state: "Certified",
    proof: "Phase C.5 certified; signals recorded with dossier, score, and hash artifacts",
  },
  {
    capability: "Risk gates",
    state: "Implemented",
    proof: "Deterministic reject reasons logged per signal",
  },
  {
    capability: "Broker reconciliation",
    state: "Built",
    proof: "Broker state vs TITAN books — mismatch halts trading",
  },
];

/** Replay/backup/shadow-pipeline tiles are sourced from
 * docs/content/PUBLIC_CLAIMS_REGISTER.md — do not change these values
 * without a corresponding register row. */
export const MILESTONES = [
  { label: "Infrastructure v1.0.0", value: "Certified" },
  { label: "Real MT5 Bridge", value: "Validated" },
  { label: "PostgreSQL Event Spine", value: "Live" },
  { label: "Replay Verification, Zero Drift", value: "1,662/1,662" },
  { label: "Restore / PITR Recovery Verified", value: "13s / 78s" },
  { label: "Continuous Health Checks", value: "24/7" },
  { label: "Telegram Critical Alerts", value: "Wired" },
  { label: "Shadow AI Pipeline", value: "Certified" },
];

export const TECH_STACK = [
  "Next.js",
  "Python",
  "PostgreSQL",
  "TimescaleDB",
  "MetaTrader 5",
  "Docker",
  "Vercel",
  "Anthropic",
  "OpenAI",
  "Telegram Alerts",
  "GitHub Actions",
];

export const PRODUCT_MODES = [
  {
    stage: "01",
    title: "Shadow Mode",
    status: "Certified",
    body: "AI runs, records decisions, and learns from market outcomes. No orders.",
  },
  {
    stage: "02",
    title: "Copilot Mode",
    status: "Upcoming",
    body: "AI proposes. Human approves or rejects. Rejections become evaluation data.",
  },
  {
    stage: "03",
    title: "Autonomous Demo",
    status: "Evidence-Gated",
    body: "Only after objective evidence, explicit approval, and safety gates.",
  },
];

export const ROADMAP = [
  { title: "Infrastructure Core", status: "completed" },
  { title: "Data Spine", status: "completed" },
  { title: "Replay and Verification", status: "completed" },
  { title: "Operational Hardening", status: "completed" },
  { title: "AI Architecture", status: "completed" },
  { title: "AI Shadow Mode", status: "completed" },
  { title: "Copilot Mode", status: "upcoming" },
  { title: "Autonomous Demo", status: "evidence-gated" },
  { title: "Institutional Platform", status: "future" },
] as const;

/** Expanded direct answers — written to be quotable by AI answer engines. */
export const FAQ_ITEMS = [
  {
    q: "What is Titan Pilot?",
    a: "Titan Pilot is an AI trading infrastructure platform built around replayable decision trails, deterministic scoring, broker reconciliation, and risk-first automation. AI is used for structured market reasoning — never for direct execution authority.",
  },
  {
    q: "Is Titan Pilot a trading bot?",
    a: "Titan Pilot is not positioned as a typical trading bot. It is an AI trading infrastructure system that separates market reasoning, deterministic scoring, risk control, execution, broker reconciliation, and replay verification into distinct, auditable layers.",
  },
  {
    q: "Does AI place trades directly?",
    a: "No. AI produces structured reasoning over a versioned market dossier. Deterministic software scores the decision, and explicit risk gates remain the final authority before any execution path. If AI fails, trading activity reduces to zero — it never increases risk.",
  },
  {
    q: "Is Titan Pilot live?",
    a: "Titan Pilot's shadow-mode AI pipeline is certified and running in production. It records every signal with a dossier, deterministic score, and hash artifacts — without placing live orders and without promising autonomous trading.",
  },
  {
    q: "What is shadow mode?",
    a: "Shadow mode runs the complete AI pipeline without placing orders. Every signal is recorded together with its dossier hash, model output, deterministic score, and risk-gate result, so the system can be evaluated on evidence before any promotion toward autonomy.",
  },
  {
    q: "How does replay verification work?",
    a: "Every decision is stored as immutable events in an append-only log. Replay verification rebuilds system state from those events and compares it against live state. If the two drift apart, the system alerts and the discrepancy is investigated before trading continues.",
  },
  {
    q: "How does Titan Pilot reduce risk?",
    a: "Titan Pilot uses deterministic pre-gates, risk gates, broker reconciliation, circuit breakers, replay verification, budget limits, and fail-closed behavior. When the system cannot prove what happened, it stops: unknown broker state halts, ambiguous execution evidence halts, and AI provider failure produces no signal.",
  },
  {
    q: "What makes Titan Pilot different from a typical trading bot?",
    a: "Typical bots obsess over entries and promise performance. Titan Pilot focuses on what happens after the idea appears: validation, scoring, risk control, broker reconciliation, recovery, replay, and auditability — built on event-sourced infrastructure with no performance claims.",
  },
  {
    q: "What markets does Titan Pilot support?",
    a: "The current validation focus is EURUSD on MetaTrader 5 infrastructure. Broader market support is future roadmap work.",
  },
  {
    q: "Is this financial advice?",
    a: "No. Titan Pilot is software infrastructure. Nothing on this website is financial, investment, or trading advice, and nothing here is a promise of trading performance. Trading involves risk.",
  },
];

export const EARLY_ACCESS_GETS = [
  "Product build updates",
  "Architecture notes",
  "Shadow-mode progress",
  "Demo access when available",
  "Technical collaboration opportunities",
];

export const EARLY_ACCESS_NOT_GETS = [
  "Guaranteed signals",
  "Financial advice",
  "Performance promises",
  "Uncontrolled live-money automation",
];

export const EARLY_ACCESS_DISCLAIMER =
  "By requesting access, you understand Titan Pilot is experimental trading infrastructure and does not provide investment advice, guaranteed returns, or live-money automation promises.";

export const MANIFESTO_PRINCIPLES = [
  {
    title: "Reasoning is not authority.",
    body: "AI can explain a market thesis, challenge assumptions, and summarize conflicting evidence. It should not be the final authority over capital. Execution authority belongs to deterministic software, explicit risk rules, and broker-verified state.",
  },
  {
    title: "Capital protection outranks opportunity.",
    body: "No signal is worth an unbounded loss. Hard limits, budgets, and circuit breakers sit below every decision — and they cannot be argued with.",
  },
  {
    title: "Every decision must be replayable.",
    body: "Every prompt, model, response, score, and gate result is recorded as immutable events. If a decision cannot be reconstructed, it should not have happened.",
  },
  {
    title: "Unknown state means stop.",
    body: "When broker truth and internal books disagree, or execution evidence is ambiguous, the system halts. Guessing is not a recovery strategy.",
  },
  {
    title: "Automation earns trust through evidence.",
    body: "Promotion from shadow mode toward autonomy is gated on recorded outcomes, explicit approval, and safety gates — never on optimism.",
  },
  {
    title: "AI should explain, challenge, and document — not override deterministic controls.",
    body: "The AI layer works from a versioned dossier. It never calculates indicators, never sees raw candles, and never bypasses risk controls. If AI fails, trading activity reduces to zero.",
  },
];

export const DISCLAIMER =
  "Titan Pilot is a software infrastructure project. Nothing on this website is financial advice, investment advice, or a promise of trading performance. Trading involves risk.";

export const PRODUCT_PRINCIPLES = [
  {
    title: "Evidence or it didn't happen.",
    body: "Every claim rendered from an AI model is visibly tagged as model output and linked to the exact dossier data it was reasoned from. Every number that comes from code — a score, a risk calculation, a price — is visibly tagged as deterministic. The two are never allowed to look the same.",
  },
  {
    title: "The default action is nothing.",
    body: "Signals that aren't acted on expire to nothing. Titan Pilot is built to make inaction feel competent, because in a risk-first pipeline, doing nothing is usually the correct outcome — not a failure state.",
  },
  {
    title: "Two states of gravity.",
    body: "Most of what the system shows is light: read-only evidence, fast to browse, safe to click around in. The small remainder — approving a trade, pulling the kill switch — is heavy: full-screen, deliberate, two steps, and fully audited. Nothing consequential ever happens from a hover or a swipe.",
  },
  {
    title: "Reconstructable past.",
    body: "Every decision can answer “as of when?” — pinned to exactly what was known at the time: the stored dossier, the model version, the scoring configuration. History is never silently re-rendered with today's code.",
  },
];

export const PRODUCT_DOCTRINES = [
  {
    title: "Never-Guess",
    body: "When the system encounters something it can't classify, it doesn't guess. An unrecognized event halts processing rather than being skipped. A reconciliation mismatch that matches no known pattern halts trading and pages a human. An AI output that fails a contract check is rejected with a closed reason code — there is no best-effort parse.",
  },
  {
    title: "Fail-Closed",
    body: "Every failure mode collapses toward no action. Can't reach the database at boot: the engine exits before trading starts. Both AI providers down: no signal, never a degraded guess. Budget cap would be exceeded: the call is refused before any money is spent. A 48-hour certification soak exercised every one of these paths in production, and each produced an explained, auditable outcome.",
  },
];

export const AUTONOMY_LADDER_DETAIL = [
  {
    stage: "Shadow",
    status: "Certified — current",
    body: "The full pipeline runs on real market data with real AI calls. Every signal is recorded with its dossier, score, and hash artifacts. Nothing is executed.",
  },
  {
    stage: "Copilot",
    status: "Designed — next",
    body: "A proposed signal reaches the desk lead with its reason codes attached. Approve or reject, with a hard expiry at the next candle close. An approved signal then walks the exact same risk gates as any other signal — there is no separate “trusted” execution path.",
  },
  {
    stage: "Autonomous Demo",
    status: "Evidence-gated — future",
    body: "Requires at least 100 recorded signals, at least 8 weeks of evidence, and objective thresholds on expectancy, calibration, and veto quality. Promotion is always a deliberate, recorded decision — never an automatic transition.",
  },
];

export const COMPETITOR_COMPARISON = [
  {
    name: "TradingView",
    theyAre: "The world's charting + social ideas platform",
    difference: "Titan Pilot's unit is the decision, not the chart. Charts here visualize the exact dossier the AI reasoned from — no social layer, and every signal comes with machine-checked citations, not likes.",
    concede: "Charting depth, asset coverage, community, price",
  },
  {
    name: "TrendSpider",
    theyAre: "Automated technical analysis tooling",
    difference: "TrendSpider automates finding patterns; Titan Pilot automates arguing about them — analyst, adversary, and deterministic score — then records the argument immutably.",
    concede: "Breadth of TA automation, backtesting UX, multi-asset scanning",
  },
  {
    name: "MetaTrader 5",
    theyAre: "The retail execution standard",
    difference: "Titan Pilot treats MT5 as a dumb execution limb. Everything MT5 lacks — provenance, approvals, replay, budget control, audit — is the product.",
    concede: "Raw execution features, broker ubiquity, indicator ecosystem",
  },
  {
    name: "Capitalise.ai",
    theyAre: "Natural-language strategy automation",
    difference: "Capitalise turns English into rules and hides the rest. Titan Pilot turns market state into an evidenced argument and shows all of it: a cited thesis, its rebuttal, and its score.",
    concede: "Onboarding simplicity, no-ops setup, multi-broker reach",
  },
  {
    name: "Tickeron",
    theyAre: "AI signal marketplace with confidence %",
    difference: "Tickeron's confidence is a marketing number; Titan Pilot's score is a hash-pinned deterministic function of visible components with the counter-argument attached.",
    concede: "Asset breadth, pattern variety, consumer price point",
  },
  {
    name: "Composer",
    theyAre: "No-code quant strategy builder / backtester",
    difference: "Composer sells hypotheticals — backtest curves. Titan Pilot sells reconstructables — hash-verified replay of what actually happened, including every no-trade.",
    concede: "Strategy composition UX, portfolio breadth, backtesting speed",
  },
  {
    name: "LuxAlgo",
    theyAre: "Premium indicator overlays",
    difference: "LuxAlgo decorates charts with proprietary signals. Every claim in Titan Pilot decomposes to dossier facts or code output — there's no proprietary mystique to defend, only evidence to show.",
    concede: "Visual polish on charts, community, low cost",
  },
  {
    name: "Bloomberg Terminal",
    theyAre: "The institutional data monopoly",
    difference: "Titan Pilot doesn't compete on data — it competes on decision accountability. Bloomberg tells you everything about the market and nothing about why your own system traded.",
    concede: "Data universe, news, chat network effects, multi-asset analytics — essentially everything except this one thing",
  },
];

export const COMPETITOR_PITCH =
  "They show you the market or a signal. Titan Pilot shows you a decision you can cross-examine.";

export const ARCHITECTURE_DEEP_DIVE = [
  {
    title: "AI cannot bypass execution.",
    body: "Three independent mechanisms enforce this, any one of which would be sufficient on its own. The AI code has no import path to execution code — a CI check fails the build if it ever does. The AI layer's only output is a recorded event; in shadow mode, nothing consumes it. And the deterministic no-trade rules the system checks against can only be tightened by AI output, never loosened.",
  },
  {
    title: "One database, three data classes.",
    body: "Decisions are event-sourced: an append-only log is the system of record, because the history is the product — audits, disputes, and forensics all require knowing exactly what the system believed and did, in order, forever. Market data (candles, calendar rows) is not event-sourced — it's high-volume and re-fetchable, with no accountability requirement of its own. What is recorded is every use of that data: each decision pins the exact input data it was built from, by hash.",
  },
  {
    title: "Replay is a proof, not a re-implementation.",
    body: "Replay doesn't re-implement the system's logic to check its own answer — it pushes the same events through the exact same production code into a scratch copy of the database, then compares every row. Rebuilding twice and hashing both results must match, or the run fails. This check runs daily, on every code change, and against every restored backup.",
  },
  {
    title: "Dependencies point one way.",
    body: "The AI and market-data code can never import execution code — mechanically enforced, not just a convention. Only one code path is allowed to write the system's official state, and the database itself backs this up: the application's role cannot delete a recorded event or bypass that single writer.",
  },
];

export const SECURITY_CAPABILITIES = [
  {
    title: "Independently audited, fixed same-day",
    body: "A security audit found issues in SSH access and backup file permissions. Both were fixed and verified the same day — SSH restricted to key-only authentication, backup files restricted to owner-only access.",
  },
  {
    title: "Secrets never leave the server",
    body: "Offsite backups are built by allowlist, not blocklist — only a sanitized database dump and a git commit hash are ever copied off the server. A blocklist approach fails open the moment a new secret is introduced; an allowlist can't.",
  },
  {
    title: "Backups are proven, not assumed",
    body: "A full restore with complete integrity verification completes in 13 seconds. Point-in-time recovery from a base backup completes in 78 seconds with zero event gap. Every week, the newest backup is restored into a throwaway copy and fully re-verified — a backup that can't pass verification isn't counted as one.",
  },
  {
    title: "AI provider failure never increases risk",
    body: "A 12-case fault-injection matrix — connection failures, DNS failures, timeouts, server errors — confirms automatic failover to a backup AI provider. If both providers are down, the system produces no signal. It never guesses.",
  },
  {
    title: "The application can't touch its own history",
    body: "The database role the application runs as cannot alter schema, and cannot delete a recorded event or a derived record — enforced by database grants and triggers, not application code that could have a bug.",
  },
  {
    title: "Failure is contained by design",
    body: "A compromised or hallucinating AI model can produce at most one recorded, validated, budget-capped document — never direct access to capital. A compromised AI provider account is capped in dollars. A stolen offsite backup exposes only a sanitized data dump and a commit hash.",
  },
  {
    title: "Verified daily, not just at launch",
    body: "A 12-check integrity suite — including replay determinism — runs automatically every day. It also runs on every code change and against every restored backup. This isn't a one-time launch audit; it's a standing, automated check.",
  },
];
