export const NAV_ITEMS = [
  { label: "Product", href: "#product" },
  { label: "Architecture", href: "#architecture" },
  { label: "AI Model", href: "#ai-model" },
  { label: "Safety", href: "#safety" },
  { label: "Roadmap", href: "#roadmap" },
  { label: "Contact", href: "#contact" },
];

export const GITHUB_URL = "https://github.com/TitanPilotHQ/Titan";

export const TRUST_BADGES = [
  "Replay Verified",
  "Risk First",
  "Event Sourced",
  "Broker Reconciled",
  "AI Shadow Mode",
];

export const WHY_CARDS = [
  {
    icon: "cpu",
    title: "Deterministic by Design",
    body: "Every computable signal is generated by software, not guessed by a model.",
  },
  {
    icon: "brain",
    title: "AI-Powered Insight",
    body: "LLMs reason over structured market dossiers instead of raw candle noise.",
  },
  {
    icon: "shield",
    title: "Risk First, Always",
    body: "Capital protection, hard limits, and fail-closed behavior sit below every AI decision.",
  },
  {
    icon: "history",
    title: "Replayable Decisions",
    body: "Each trade can be reconstructed from immutable events and verified after the fact.",
  },
];

export const ARCHITECTURE_FLOW = [
  "Market Data",
  "Dossier Builder",
  "AI Analyst",
  "Devil's Advocate",
  "Deterministic Scorer",
  "Trading Gate",
  "Risk Gate",
  "MT5 Execution",
  "Broker Reconciliation",
  "Event Log",
  "Replay / Verify",
];

export const ARCHITECTURE_LAYERS = [
  {
    title: "Market Dossier",
    body: "Structured multi-timeframe data computed by deterministic modules.",
  },
  {
    title: "AI Reasoning",
    body: "Agents reason, challenge, and explain. They do not execute.",
  },
  {
    title: "Deterministic Scoring",
    body: "Pure code combines evidence, objections, macro risk, and cost constraints.",
  },
  {
    title: "Risk Gate",
    body: "Final deterministic risk authority before any execution path.",
  },
  {
    title: "Broker Reconciliation",
    body: "Broker truth is compared against TITAN books. Unknown or ambiguous state halts.",
  },
  {
    title: "Replay Verification",
    body: "State is rebuilt from immutable events to prove the system has not drifted.",
  },
];

export const DECISION_STEPS = [
  "H1 candle closes",
  "Pre-gate checks market conditions",
  "Dossier is built and hashed",
  "Technical Analyst produces thesis",
  "Devil's Advocate challenges it",
  "Deterministic scorer calculates result",
  "Signal is recorded in shadow mode",
  "Risk engine remains final authority",
  "Replay can reconstruct the full story",
];

export const AI_CARDS = [
  {
    title: "Dossier First",
    body: "AI receives structured, validated context.",
  },
  {
    title: "Adversarial Review",
    body: "Every thesis is challenged before scoring.",
  },
  {
    title: "No Guessing",
    body: "Malformed, ambiguous, or unsupported outputs are rejected.",
  },
  {
    title: "Shadow Before Autonomy",
    body: "The system earns promotion through evidence, not optimism.",
  },
];

export const SAFETY_RULES = [
  { condition: "Unknown broker state", response: "Halt" },
  { condition: "Ambiguous execution evidence", response: "Halt" },
  { condition: "AI provider failure", response: "No signal" },
  { condition: "Budget exhausted", response: "No signal" },
  { condition: "Calendar / news stale", response: "Widen no-trade window" },
  { condition: "Database unavailable", response: "No trading" },
  { condition: "Replay drift", response: "Alert and investigate" },
];

export const MILESTONES = [
  { label: "Infrastructure v1.0.0", value: "Certified" },
  { label: "Real MT5 Bridge", value: "Validated" },
  { label: "PostgreSQL Event Spine", value: "Live" },
  { label: "Replay Verification", value: "Active" },
  { label: "PITR + Offsite Backups", value: "Verified" },
  { label: "Continuous Health Checks", value: "24/7" },
  { label: "Telegram Critical Alerts", value: "Wired" },
  { label: "Shadow AI Pipeline", value: "Running" },
];

export const TECH_STACK = [
  "Next.js",
  "Python",
  "PostgreSQL",
  "TimescaleDB",
  "MetaTrader 5",
  "Docker",
  "Vercel",
  "Anthropic",
  "OpenAI",
  "Telegram Alerts",
  "GitHub Actions",
];

export const PRODUCT_MODES = [
  {
    stage: "01",
    title: "Shadow Mode",
    status: "In Validation",
    body: "AI runs, records decisions, and learns from market outcomes. No orders.",
  },
  {
    stage: "02",
    title: "Copilot Mode",
    status: "Upcoming",
    body: "AI proposes. Human approves or rejects. Rejections become evaluation data.",
  },
  {
    stage: "03",
    title: "Autonomous Demo",
    status: "Evidence-Gated",
    body: "Only after objective evidence, explicit approval, and safety gates.",
  },
];

export const ROADMAP = [
  { title: "Infrastructure Core", status: "completed" },
  { title: "Data Spine", status: "completed" },
  { title: "Replay and Verification", status: "completed" },
  { title: "Operational Hardening", status: "completed" },
  { title: "AI Architecture", status: "completed" },
  { title: "AI Shadow Mode", status: "in-validation" },
  { title: "Copilot Mode", status: "upcoming" },
  { title: "Autonomous Demo", status: "evidence-gated" },
  { title: "Institutional Platform", status: "future" },
] as const;

export const FAQ_ITEMS = [
  {
    q: "What is Titan Pilot?",
    a: "Titan Pilot is an AI trading infrastructure platform designed around deterministic execution, AI-assisted reasoning, replayable decisions, and risk-first automation.",
  },
  {
    q: "Is Titan Pilot a trading bot?",
    a: "Titan Pilot is more than a trading bot. It is an infrastructure platform that combines market analysis, AI reasoning, risk gates, broker reconciliation, event sourcing, and replay verification.",
  },
  {
    q: "Does AI place trades directly?",
    a: "No. AI may propose signals, but deterministic software gates, scores, validates, and controls execution.",
  },
  {
    q: "What is shadow mode?",
    a: "Shadow mode runs the full AI pipeline without placing orders. It records signals and outcomes so the system can be evaluated before promotion.",
  },
  {
    q: "How does Titan Pilot reduce risk?",
    a: "Titan Pilot uses deterministic pre-gates, risk gates, broker reconciliation, circuit breakers, replay verification, budget limits, and fail-closed behavior.",
  },
  {
    q: "What makes Titan Pilot different from a typical trading bot?",
    a: "Typical bots focus on entries. Titan Pilot focuses on the entire lifecycle: analysis, validation, execution, reconciliation, recovery, replay, and auditability — built on event-sourced, replayable infrastructure.",
  },
  {
    q: "What markets does Titan Pilot support?",
    a: "The current validation focus is EURUSD on MetaTrader 5 infrastructure. Broader market support is future roadmap work.",
  },
  {
    q: "Is this financial advice?",
    a: "No. Titan Pilot is software infrastructure. Nothing on the website is financial or investment advice.",
  },
];

export const DISCLAIMER =
  "Titan Pilot is a software infrastructure project. Nothing on this website is financial advice, investment advice, or a promise of trading performance. Trading involves risk.";
